services:
  mysqldb:
    image: mysql:8.0
    container_name: mysql_server
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: test

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    volumes:
      - $HOME/nodeapp:/code
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - mysqldb
    environment:
      PORT: 8080
      LOG_LEVEL: info
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'root'
      DB_PASSWORD: 'test'
      DB_NAME: restaurant
      SECRET_KEY: fwv3dkkbs1db5kghjsp2k
      DATABASE_URL: mysql://root:test@mysqldb:3306/restaurant
